# -*- coding: utf-8 -*-
"""NYU_DL_24_Contest_starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8uV2eRw7vFyXbeRIqowyGIq6enE7TvQ

# Math Question Answer Verification Competition

## Starter Code

Borrowed from [official Unsloth implementation](https://colab.research.google.com/drive/1Ys44kVvmeZtnICzWz0xgpRnrIOjZAuxp?usp=sharing#scrollTo=MKX_XKs_BNZR)
"""

from google.colab import drive
drive.mount('/content/drive')

# %%capture
# This cell will take time
!pip install unsloth
# Also get the latest nightly Unsloth!
!pip uninstall unsloth -y && pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # RoPE scaling, so we maintain unchanged here
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

"""## Load model and wrap with LoRA adapters"""

model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    # choose the modules: attention layers ["q_proj", "v_proj"], feed forward layers ["down_proj", "up_proj"]
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    # usally 2 * rank
    lora_alpha = 32,
    # add some dropout to prevent overfitting
    lora_dropout = 0.1, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

"""## Competition dataset"""

# download and load competition dataset

from datasets import load_dataset
dataset = load_dataset("ad6398/nyu-dl-teach-maths-comp")

# Print dataset details
print(dataset)

# Check the columns and a sample row
print(dataset["train"].column_names)
print(dataset["train"][0])

"""Since there's no validation sets in the given dataset, we need to create one"""

# Create a validation split (80% train, 20% validation)
train_val_split = dataset["train"].train_test_split(test_size=0.2, seed=42)
train_data = train_val_split["train"]
validation_data = train_val_split["test"]

# Check the sizes
print(f"Training set size: {len(train_data)}")
print(f"Validation set size: {len(validation_data)}")
print(f"Test set size: {len(dataset['test'])}")

import matplotlib.pyplot as plt
import numpy as np

# Analyze token lengths for the "question" and "solution" fields
train_data_sample = train_data.select(range(1000))  # Sample to speed up analysis

question_lengths = [len(tokenizer(question)["input_ids"]) for question in train_data_sample["question"]]
solution_lengths = [len(tokenizer(solution)["input_ids"]) for solution in train_data_sample["solution"]]

# Plot token length distributions
plt.hist(question_lengths, bins=50, alpha=0.5, label="Questions")
plt.hist(solution_lengths, bins=50, alpha=0.5, label="Solutions")
plt.xlabel("Token Length")
plt.ylabel("Frequency")
plt.legend()
plt.title("Token Length Distribution")
plt.show()

# Statistics
print(f"Mean question length: {np.mean(question_lengths)}")
print(f"95th percentile question length: {np.percentile(question_lengths, 95)}")
print(f"Mean solution length: {np.mean(solution_lengths)}")
print(f"95th percentile solution length: {np.percentile(solution_lengths, 95)}")

prompt = """You are a great mathematician and you are tasked with finding if an answer to a given maths question is correct or not. Yout response should be 'True' if correct, otherwise 'False'. Below is Question and Answer.


### Question:
{}

### Answer:
{}

### Solution:
{}

### Output:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN
def formatting_prompts_func(examples):
    question = examples["question"]
    ans       = examples["answer"]
    solution = examples["solution"]
    output      = examples["is_correct"]
    texts = []
    for instruction, input, sol, output in zip(question, ans, solution, output):
        # Must add EOS_TOKEN, otherwise your generation will go on forever!
        text = prompt.format(instruction, input, sol, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }

# Process the training dataset and generate prompt for each datapoint
train_dataset = train_data.map(formatting_prompts_func, batched = True)
# Process the validation dataset
validation_dataset = validation_data.map(formatting_prompts_func, batched=True)

#print a smaple training example
train_dataset['text'][0]

small_train_dataset = train_dataset.shuffle(seed=42).select(range(int(len(train_dataset) * 0.01)))
small_validation_dataset = validation_dataset.shuffle(seed=42).select(range(int(len(validation_dataset) * 0.001)))
print(f"Training set size: {len(small_train_dataset)}")
print(f"Validation set size: {len(small_validation_dataset)}")

"""## SFT"""

from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

training_args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 100,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 1000,
        learning_rate = 1e-5,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 10,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
        eval_steps=10,                # Evaluate every 10 steps
        evaluation_strategy="steps",  # Use step-based evaluation
        save_strategy="steps",        # Save the model every 10 steps
        save_steps=10,
        load_best_model_at_end=True
    )

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = small_train_dataset,
    eval_dataset=small_validation_dataset,
    dataset_text_field = "text",
    max_seq_length = 768,
    dataset_num_proc = 4,
    packing = False, # Can make training 5x faster for short sequences.
    args = training_args
)

trainer_stats = trainer.train()

"""## inference"""

# Sample inferene data point
test_dataset = dataset['test']

sample_ques = test_dataset['question'][0]
sample_ans = test_dataset['answer'][0]
sample_solu = test_dataset['solution'][0]

# Running inference on single test
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
input_prompt = prompt.format(
        sample_ques, # ques
        sample_ans, # given answer
        sample_solu,
        "", # output - leave this blank for generation! LLM willl generate is it is True or False
    )

print("Input Promt:\n", input_prompt)
inputs = tokenizer(
[
    input_prompt
], return_tensors = "pt").to("cuda")

input_shape = inputs['input_ids'].shape
input_token_len = input_shape[1] # 1 because of batch
outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
# you can get the whole generated text by uncommenting the below line
# text_generated = tokenizer.batch_decode([outputs, skip_special_tokens=True)

response = tokenizer.batch_decode([outputs[0][input_token_len:]], skip_special_tokens=True)
response

"""## saving model"""

model.save_pretrained("lora_model") # Local saving
tokenizer.save_pretrained("lora_model")

if True:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

"""# Batch Inference

"""

prompt = """You are a great mathematician and you are tasked with finding if an answer to a given maths question is correct or not. Yout response should be 'True' if correct, otherwise 'False'. Below is Question and Answer.


### Question:
{}

### Answer:
{}

### Solution:
{}

### Output:
{}"""

def formatting_test_prompts_func(examples):
    question = examples["question"]
    ans       = examples["answer"]
    solution = examples["solution"]
    texts = []
    for instruction, input, sol in zip(question, ans, solution):
        text = prompt.format(instruction, input, sol, "")
        texts.append(text)
    return { "text" : texts, }


test_text_dataset = dataset['test'].map(formatting_test_prompts_func, batched = True,)

# Running inference on batch test

FastLanguageModel.for_inference(model)

test_dataset = test_text_dataset['text']
batch_size = 4
batch_number = int(len(test_dataset)/batch_size)
output_label = []

for i in range(batch_number):
  print("batch-num:", i)
  inputs_prompt = []
  for j in range(batch_size):
      index = batch_size * i + j
      inputs_prompt.append(test_dataset[index])

  inputs = tokenizer(inputs_prompt, return_tensors = "pt", padding=True, truncation=True).to("cuda")
  outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
  text_generated = tokenizer.batch_decode(outputs, skip_special_tokens=True)
  for text in text_generated:
    output_label.append(text.splitlines()[-1])

print(len(output_label))

import csv

cnt = 0
csv_data = [["ID", "is_correct"]]
for i in range(len(output_label)):
  if output_label[i] == 'True':
    cnt = cnt + 1
    csv_data.append([i, True])
  else:
    csv_data.append([i, False])

# Write to CSV file
with open('data.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(csv_data)

print("successfully write to data.csv")

from google.colab import files
files.download('data.csv')